slice_name: 'Driver acceptance rate'
description: 'Offers accepted out of offers made.'
uuid: '5c9c0c26-c7e9-5939-90c6-327dc344b508'
dataset_uuid: '14a85160-f570-562c-84b0-0cf132d40c30'
version: '1.0.0'
viz_type: 'big_number_total'
cache_timeout: null
certified_by: null
certification_details: null
query_context: null
params: {"metric": "acceptance_rate", "adhoc_filters": [], "granularity_sqla": "hour", "time_range": "Last week", "y_axis_format": ",.1%", "header_font_size": 0.4, "subheader_font_size": 0.125, "subheader": "Offers accepted out of offers made.", "viz_type": "big_number_total", "datasource": "1__table"}
