slice_name: 'Fulfilment rate'
description: 'Completed out of every request that reached an ending.'
uuid: '9ec5db02-d5f3-535f-b00f-89debd2df9e1'
dataset_uuid: 'da686763-4999-5db3-b61a-1f15ac41d69d'
version: '1.0.0'
viz_type: 'big_number_total'
cache_timeout: null
certified_by: null
certification_details: null
query_context: null
params: {"metric": "fulfilment_rate", "adhoc_filters": [], "granularity_sqla": "hour", "time_range": "Last week", "y_axis_format": ",.1%", "header_font_size": 0.4, "subheader_font_size": 0.125, "subheader": "Completed out of every request that reached an ending.", "viz_type": "big_number_total", "datasource": "1__table"}
