log_keys:
  id:
    provider: incremental
    start: 1000
    increment: 1
  date:
    provider: date
    start_date: 2025-01-01
    end_date: 2025-12-31
  time:
    provider: time
    format: HH:MM:SS.MS
  passenger_id:
    provider: uuid4
  driver_id:
    provider: uuid4
  pick_up_lat:
    provider: latitude
    min: 40.5
    max: 41.0
  pick_up_lon:
    provider: longitude
    min: -74.3
    max: -73.7
  drop_off_lat:
    provider: latitude
    min: 40.5
    max: 41.0
  drop_off_lon:
    provider: longitude
    min: -74.3
    max: -73.7
  price:
    provider: random_number
    min: 10
    max: 100
  ride_status:
    provider: random_element
    weights: [7.0, 3.0]
